/**
 * Chat SSE Events — Extended from Open Design's `ChatSseEvent` with MULTIMODAL event types.
 *
 * OD Pattern: `ChatSseEvent` is a discriminated union of `SseTransportEvent` members
 * covering the lifecycle of a chat run: start → agent (streaming) → stdout/stderr → end/error.
 * The `DaemonAgentPayload` type is itself a discriminated union keyed on `type`, enabling
 * exhaustive switching on agent streaming events (text_delta, thinking_delta, tool_use, etc.).
 *
 * Extension: We add 6 new multimodal event types to `DaemonAgentPayload`:
 *   - image_generated   — an image was produced by a media generation model
 *   - video_generated   — a video was produced by a media generation model
 *   - audio_generated   — audio was produced by a media generation model
 *   - model_3d_generated — a 3D model was produced
 *   - artifact_preview  — a preview of an in-progress artifact is available
 *   - artifact_ready    — the final artifact is ready for consumption
 *
 * These follow the same discriminated-union pattern as OD's `tool_use`, `tool_result`, etc.
 */

import type { SseTransportEvent } from './common';
import type { SseErrorPayload } from '../errors';

// ---------------------------------------------------------------------------
// Protocol version — bumped when the event vocabulary changes
// ---------------------------------------------------------------------------
export const CHAT_SSE_PROTOCOL_VERSION = 2;

// ---------------------------------------------------------------------------
// Start payload — mirrors OD's ChatSseStartPayload
// ---------------------------------------------------------------------------
export interface ChatSseStartPayload {
  runId?: string;
  agentId?: string;
  bin: string;
  protocolVersion?: typeof CHAT_SSE_PROTOCOL_VERSION;
  /** Legacy daemon-internal absolute cwd. Kept for compatibility. */
  cwd?: string | null;
  projectId?: string | null;
  model?: string | null;
  reasoning?: string | null;
}

// ---------------------------------------------------------------------------
// Chunk payload — for stdout/stderr streaming
// ---------------------------------------------------------------------------
export interface ChatSseChunkPayload {
  chunk: string;
}

// ---------------------------------------------------------------------------
// End payload — mirrors OD's ChatSseEndPayload
// ---------------------------------------------------------------------------
export interface ChatSseEndPayload {
  code: number | null;
  signal?: string | null;
  status?: 'succeeded' | 'failed' | 'canceled';
  /** True when a `failed` run can be recovered by resuming the agent session. */
  resumable?: boolean;
}

// ---------------------------------------------------------------------------
// Media artifact reference — shared structure for multimodal generated outputs
// ---------------------------------------------------------------------------

export interface MediaArtifactRef {
  /** Unique id for this generated artifact. */
  artifactId: string;
  /** The project that owns this artifact. */
  projectId: string;
  /** MIME type of the generated content. */
  mime: string;
  /** Size in bytes, if known. */
  sizeBytes?: number;
  /** Daemon-relative URL to fetch the artifact. */
  url: string;
  /** The model that produced this artifact. */
  model: string;
  /** The surface that was requested. */
  surface: 'image' | 'video' | 'audio' | 'model-3d';
}

// ---------------------------------------------------------------------------
// DaemonAgentPayload — the core discriminated union
// Extended from OD's 12-variant union to 18 variants with multimodal support.
// ---------------------------------------------------------------------------
export type DaemonAgentPayload =
  // --- OD original variants (preserved) ---
  | { type: 'status'; label: string; model?: string; ttftMs?: number; detail?: string }
  | { type: 'text_delta'; delta: string }
  | { type: 'thinking_delta'; delta: string }
  | { type: 'thinking_start' }
  | { type: 'tool_use'; id: string; name: string; input: unknown }
  /** Live-only incremental tool-input fragment while the model is still streaming. */
  | { type: 'tool_input_delta'; id: string; name: string; delta: string }
  | { type: 'tool_result'; toolUseId: string; content: string; isError?: boolean }
  | { type: 'usage'; usage?: { input_tokens?: number; output_tokens?: number }; costUsd?: number; durationMs?: number }
  | { type: 'fabricated_role_marker'; marker: string; messageId?: string }
  | { type: 'raw'; line: string }

  // --- MULTIMODAL extensions (NEW) ---

  /**
   * An image was generated by a media model. The UI can render a preview
   * immediately; the full-resolution file is at `artifact.url`.
   */
  | { type: 'image_generated'; artifact: MediaArtifactRef; prompt: string; aspectRatio?: string }

  /**
   * A video was generated. The UI can show a thumbnail or inline player.
   * For long-running renders, `taskId` is provided for polling.
   */
  | { type: 'video_generated'; artifact: MediaArtifactRef; prompt: string; durationSeconds?: number; taskId?: string }

  /**
   * Audio was generated. The UI can render an inline player.
   */
  | { type: 'audio_generated'; artifact: MediaArtifactRef; prompt: string; durationSeconds?: number; voiceId?: string }

  /**
   * A 3D model was generated. The UI can render a viewer/thumbnail.
   */
  | { type: 'model_3d_generated'; artifact: MediaArtifactRef; prompt: string; format?: string }

  /**
   * A preview of an in-progress artifact is available (e.g. a low-res image
   * while the full render continues, or a draft video frame).
   */
  | { type: 'artifact_preview'; artifactId: string; surface: 'image' | 'video' | 'audio' | 'model-3d'; previewUrl: string; progress?: number }

  /**
   * The final artifact is ready for consumption. Emitted after
   * image_generated / video_generated / audio_generated / model_3d_generated
   * to signal that all post-processing (formatting, thumbnails, etc.) is done.
   */
  | { type: 'artifact_ready'; artifactId: string; surface: 'image' | 'video' | 'audio' | 'model-3d'; url: string; mime: string };

// ---------------------------------------------------------------------------
// ChatSseEvent — the top-level discriminated union for the chat SSE stream.
// Extended from OD's 6-event union to include multimodal agent events.
// ---------------------------------------------------------------------------
export type ChatSseEvent =
  | SseTransportEvent<'start', ChatSseStartPayload>
  | SseTransportEvent<'agent', DaemonAgentPayload>
  | SseTransportEvent<'stdout', ChatSseChunkPayload>
  | SseTransportEvent<'stderr', ChatSseChunkPayload>
  | SseTransportEvent<'error', SseErrorPayload>
  | SseTransportEvent<'end', ChatSseEndPayload>;

/**
 * Helper: all known `DaemonAgentPayload.type` values.
 * Useful for runtime validation and exhaustive switch checking.
 */
export const DAEMON_AGENT_PAYLOAD_TYPES = [
  'status',
  'text_delta',
  'thinking_delta',
  'thinking_start',
  'tool_use',
  'tool_input_delta',
  'tool_result',
  'usage',
  'fabricated_role_marker',
  'raw',
  // Multimodal extensions
  'image_generated',
  'video_generated',
  'audio_generated',
  'model_3d_generated',
  'artifact_preview',
  'artifact_ready',
] as const satisfies readonly DaemonAgentPayload['type'][];

/**
 * The set of multimodal event types — useful for filtering or gating
 * media-only UI paths.
 */
export const MULTIMODAL_AGENT_PAYLOAD_TYPES = [
  'image_generated',
  'video_generated',
  'audio_generated',
  'model_3d_generated',
  'artifact_preview',
  'artifact_ready',
] as const;

export type MultimodalAgentPayloadType = typeof MULTIMODAL_AGENT_PAYLOAD_TYPES[number];

/**
 * Check whether a `DaemonAgentPayload` is one of the multimodal types.
 */
export function isMultimodalAgentPayload(
  payload: DaemonAgentPayload,
): payload is Extract<DaemonAgentPayload, { type: MultimodalAgentPayloadType }> {
  return (MULTIMODAL_AGENT_PAYLOAD_TYPES as readonly string[]).includes(payload.type);
}
